#pragma once

#include <string_view>
#include <string>
#include <vector>

#include "World.hpp"

namespace bunker {

struct ValidationIssue;

struct SemanticAnchorBatchResult {
    int createdCount = 0;
    int lastCreatedObjectIndex = -1;
    std::vector<int> createdObjectIndices{};
    std::vector<std::string> createdScriptTags{};
};

struct SemanticDependencyEdge {
    int sourceObjectIndex = -1;
    int dependencyObjectIndex = -1;
    std::string sourceScriptTag;
    std::string dependencyScriptTag;
    bool dependencyPresent = false;
};

struct SemanticLayoutOptions {
    bool preserveManualPlacement = true;
};

std::vector<std::string_view> RequiredSemanticDependencyTags(std::string_view scriptTag);
std::vector<SemanticDependencyEdge> BuildSemanticDependencyGraph(const World& world, int rootObjectIndex);
std::vector<int> CollectSemanticDependencyObjectIndices(const World& world, int rootObjectIndex, bool includeRoot = true);
bool IsAutoGeneratedSemanticAnchor(const MapObject& object);
bool IsPinnedSemanticAnchor(const MapObject& object);
bool PinSemanticAnchorPlacement(MapObject& object, bool pinned);
bool AdoptSemanticAnchorAsAuthored(MapObject& object, bool pinPlacement = true);
int AdoptAllAutoCreatedSemanticAnchors(World& world, std::string& statusText);
int AdoptSemanticDependencyChainAsAuthored(World& world, int rootObjectIndex, bool includeRoot, std::string& statusText);
int AutoLayoutSemanticDependencyChain(World& world, int rootObjectIndex, std::string& statusText, const SemanticLayoutOptions& options);
int AutoLayoutSemanticDependencyChain(World& world, int rootObjectIndex, std::string& statusText);
bool AlignObjectToDescriptorDefaults(MapObject& object, bool overwriteLinkTarget = true);
bool CanAutoFixValidationIssue(const ValidationIssue& issue);
bool AutoFixValidationIssue(World& world, const ValidationIssue& issue, std::string& statusText);
int AutoFixSafeValidationIssues(World& world, std::string& statusText);
bool CanCreateMissingDependencyAnchor(const ValidationIssue& issue);
bool CreateMissingDependencyAnchorForIssue(World& world, const ValidationIssue& issue, int& createdObjectIndex, std::string& statusText);
SemanticAnchorBatchResult CreateMissingDependencyAnchorsCascade(World& world, std::string& statusText);

}  // namespace bunker
